### ISSUE TITLE
The subscription doesn't work

### ISSUE THREAD

**Issue by Maxdeso** [tgbot-collection/ytdlbot#122]
Error: 
```
Traceback (most recent call last):
  File "/ytdlbot/ytdlbot/ytdl_bot.py", line 111, in subscribe_handler
    result = vip.subscribe_channel(chat_id, link)
  File "/ytdlbot/ytdlbot/limit.py", line 86, in subscribe_channel
    data = self.get_channel_info(share_link)
  File "/ytdlbot/ytdlbot/limit.py", line 137, in get_channel_info
    channel_id = canonical_link.split("https://www.youtube.com/channel/")[1]
IndexError: list index out of range
```

**Comment by BennyThink** [comment]
Thanks for notifying. It should be fixed. Please pull the latest code base

**Comment by Maxdeso** [comment]
The problem remains

**Comment by BennyThink** [comment]
Can you share me the link?

**Comment by Maxdeso** [comment]
I found the reason. Doesn't work with links like https://www.youtube.com/c/<channel_name>

**Comment by BennyThink** [comment]
You need to share the entire link so I can reproduce.

**Comment by Maxdeso** [comment]
I switched to mariadb and everything was fine.

**Comment by BennyThink** [comment]
There was a schema change before.
