### ISSUE TITLE
Bot cannot autenticate.

### ISSUE THREAD

**Issue by gabrielecaruso** [tgbot-collection/ytdlbot#131]
Hello,
i receive this error if i try to use the python script:

[2022-07-05 15:00:08 session.py:174 I] Session stopped
Traceback (most recent call last):
  File "/root/ytdlbot/ytdlbot/ytdl_bot.py", line 390, in <module>
    app.run()
  File "/usr/local/lib/python3.9/dist-packages/pyrogram/methods/utilities/run.py", line 58, in run
    self.start()
  File "/usr/local/lib/python3.9/dist-packages/pyrogram/sync.py", line 66, in async_to_sync_wrap
    return loop.run_until_complete(coroutine)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.9/dist-packages/pyrogram/methods/utilities/start.py", line 56, in start
    await self.authorize()
  File "/usr/local/lib/python3.9/dist-packages/pyrogram/client.py", line 280, in authorize
    return await self.sign_in_bot(self.bot_token)
  File "/usr/local/lib/python3.9/dist-packages/pyrogram/methods/auth/sign_in_bot.py", line 46, in sign_in_bot
    r = await self.send(
  File "/usr/local/lib/python3.9/dist-packages/pyrogram/methods/advanced/send.py", line 77, in send
    r = await self.session.send(
  File "/usr/local/lib/python3.9/dist-packages/pyrogram/session/session.py", line 362, in send
    return await self._send(data, timeout=timeout)
  File "/usr/local/lib/python3.9/dist-packages/pyrogram/session/session.py", line 332, in _send
    RPCError.raise_it(result, type(data))
  File "/usr/local/lib/python3.9/dist-packages/pyrogram/errors/rpc_error.py", line 91, in raise_it
    raise getattr(
pyrogram.errors.exceptions.bad_request_400.ApiIdInvalid: Telegram says: [400 API_ID_INVALID] - The api_id/api_hash combination is invalid (caused by "auth.ImportBotAuthorization")

the strange thing is that it works using docker...with all the same informations like APP_ID token ... (i created even another APP_ID but nothing changes)...any help?

**Comment by BennyThink** [comment]
The api_id/api_hash combination is invalid 


For docker you need to use env file
