### ISSUE TITLE
how to correctlly setting up celery with flower.

### ISSUE THREAD

**Issue by thelittlerocket** [tgbot-collection/ytdlbot#158]
Hi there,

Thanks for the project, 
Try to setting up ytdlbot with flower, using ```echo  'import dbm;dbm.open("data/flower","n");exit()'| python3``` to create the db, but when I docker-compose up, the script complaint that flower is a directory
```
ytdlbot-flower-1 exited with code 1
ytdlbot-flower-1  | Traceback (most recent call last):
ytdlbot-flower-1  |   File "/usr/local/bin/celery", line 8, in <module>
ytdlbot-flower-1  |     sys.exit(main())
ytdlbot-flower-1  |   File "/usr/local/lib/python3.10/site-packages/celery/__main__.py", line 15, in main
ytdlbot-flower-1  |     sys.exit(_main())
ytdlbot-flower-1  |   File "/usr/local/lib/python3.10/site-packages/celery/bin/celery.py", line 217, in main
ytdlbot-flower-1  |     return celery(auto_envvar_prefix="CELERY")
ytdlbot-flower-1  |   File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
ytdlbot-flower-1  |     return self.main(*args, **kwargs)
ytdlbot-flower-1  |   File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1055, in main
ytdlbot-flower-1  |     rv = self.invoke(ctx)
ytdlbot-flower-1  |   File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
ytdlbot-flower-1  |     return _process_result(sub_ctx.command.invoke(sub_ctx))
ytdlbot-flower-1  |   File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
ytdlbot-flower-1  |     return ctx.invoke(self.callback, **ctx.params)
ytdlbot-flower-1  |   File "/usr/local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
ytdlbot-flower-1  |     return __callback(*args, **kwargs)
ytdlbot-flower-1  |   File "/usr/local/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
ytdlbot-flower-1  |     return f(get_current_context(), *args, **kwargs)
ytdlbot-flower-1  |   File "/usr/local/lib/python3.10/site-packages/flower/command.py", line 43, in flower
ytdlbot-flower-1  |     flower = Flower(capp=app, options=options, **settings)
ytdlbot-flower-1  |   File "/usr/local/lib/python3.10/site-packages/flower/app.py", line 62, in __init__
ytdlbot-flower-1  |     self.events = events or Events(
ytdlbot-flower-1  |   File "/usr/local/lib/python3.10/site-packages/flower/events.py", line 142, in __init__
ytdlbot-flower-1  |     state = shelve.open(self.db)
ytdlbot-flower-1  |   File "/usr/local/lib/python3.10/shelve.py", line 243, in open
ytdlbot-flower-1  |     return DbfilenameShelf(filename, flag, protocol, writeback)
ytdlbot-flower-1  |   File "/usr/local/lib/python3.10/shelve.py", line 227, in __init__
ytdlbot-flower-1  |     Shelf.__init__(self, dbm.open(filename, flag), protocol, writeback)
ytdlbot-flower-1  |   File "/usr/local/lib/python3.10/dbm/__init__.py", line 95, in open
ytdlbot-flower-1  |     return mod.open(file, flag, mode)
ytdlbot-flower-1  | _gdbm.error: [Errno 21] Is a directory: 'flower'
ytdlbot-flower-1 exited with code 1
```
can you point me in a direction? any help would be appreciated.
thanks,

**Comment by thelittlerocket** [comment]
After manually mounting flower.db to /ytdlbot/ytdlbot/flower.db, it seems to work now, but if I set ENABLE_CELERY to true, it will find the workers and select a worker when I try to download, but it won't start downloading.
```
ytdlbot-ytdl-1    | [2022-11-01 10:26:32 tasks.py:422 I] Selecting worker 8ed68e3e93c9 from ['2d42332cde0a', '2d42332cde0a', '2d42332cde0a', '2d42332cde0a',................'8ed68e3e93c9', '8ed68e3e93c9'] in 1.11s
```

**Comment by dlcvietnam** [comment]
> 

meeting that bug too. Can you tell me how to fix it?
