### ISSUE TITLE
ytdlbot-flower-1镜像启动容器报错导致启动不了

### ISSUE THREAD

**Issue by daybreak-git** [tgbot-collection/ytdlbot#191]
Traceback (most recent call last):
  File "/usr/local/bin/celery", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/site-packages/celery/__main__.py", line 15, in main
    sys.exit(_main())
  File "/usr/local/lib/python3.10/site-packages/celery/bin/celery.py", line 217, in main
    return celery(auto_envvar_prefix="CELERY")
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/flower/command.py", line 43, in flower
    flower = Flower(capp=app, options=options, **settings)
  File "/usr/local/lib/python3.10/site-packages/flower/app.py", line 62, in __init__
    self.events = events or Events(
  File "/usr/local/lib/python3.10/site-packages/flower/events.py", line 142, in __init__
    state = shelve.open(self.db)
  File "/usr/local/lib/python3.10/shelve.py", line 243, in open
    return DbfilenameShelf(filename, flag, protocol, writeback)
  File "/usr/local/lib/python3.10/shelve.py", line 227, in __init__
    Shelf.__init__(self, dbm.open(filename, flag), protocol, writeback)
  File "/usr/local/lib/python3.10/dbm/__init__.py", line 95, in open
    return mod.open(file, flag, mode)
_gdbm.error: [Errno 21] Is a directory: 'flower'

**Comment by BennyThink** [comment]
https://github.com/tgbot-collection/ytdlbot#322-setup-flower-db-in-ytdlbotytdlbotdata
