### ISSUE TITLE
91视频链接下载不了

### ISSUE THREAD

**Issue by daybreak-git** [tgbot-collection/ytdlbot#193]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/pyrogram/dispatcher.py", line 224, in handler_worker
    await self.loop.run_in_executor(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/ytdlbot/ytdlbot/ytdl_bot.py", line 87, in wrapper
    return func(client, message)
  File "/ytdlbot/ytdlbot/ytdl_bot.py", line 362, in download_handler
    ytdl_download_entrance(bot_msg, client, url)
  File "/ytdlbot/ytdlbot/tasks.py", line 143, in ytdl_download_entrance
    ytdl_normal_download(bot_msg, client, url)
  File "/ytdlbot/ytdlbot/tasks.py", line 256, in ytdl_normal_download
    result = ytdl_download(url, temp_dir.name, bot_msg)
  File "/ytdlbot/ytdlbot/downloader.py", line 210, in ytdl_download
    result, err_msg = check_quota(detect_filesize(url), chat_id)
  File "/ytdlbot/ytdlbot/downloader.py", line 329, in detect_filesize
    info_dict = ydl.extract_info(url, download=False)
  File "/usr/local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1491, in extract_info
    return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
  File "/usr/local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1520, in wrapper
    self.report_error(str(e), e.format_traceback())
  File "/usr/local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1012, in report_error
    self.trouble(f'{self._format_err("ERROR:", self.Styles.ERROR)} {message}', *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 952, in trouble
    raise DownloadError(message, exc_info)
yt_dlp.utils.DownloadError: ERROR: [91porn] 26ec66f6b16249ae097b: Unable to extract title; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

**Comment by BennyThink** [comment]
https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md
