### ISSUE TITLE
Error -2 connecting to redis

### ISSUE THREAD

**Issue by tizosa** [tgbot-collection/ytdlbot#229]
Hi, 
Can you help me please set up this bot? I'am getting:
Error -2 connecting to redis 
`dispatcher.py:235 E] Error -2 connecting to redis:6379. Name does not resolve.`

Here is full log
`
[2023-04-27 21:12:30 ytdl_bot.py:116 I] Welcome to youtube-dl bot!
[2023-04-27 21:12:39 dispatcher.py:235 E] Error -2 connecting to redis:6379. Name does not resolve.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/redis/connection.py", line 698, in connect
    sock = self.retry.call_with_retry(
  File "/usr/local/lib/python3.10/site-packages/redis/retry.py", line 46, in call_with_retry
    return do()
  File "/usr/local/lib/python3.10/site-packages/redis/connection.py", line 699, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
  File "/usr/local/lib/python3.10/site-packages/redis/connection.py", line 955, in _connect
    for res in socket.getaddrinfo(
  File "/usr/local/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name does not resolve
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/pyrogram/dispatcher.py", line 224, in handler_worker
    await self.loop.run_in_executor(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/ytdlbot/ytdlbot/ytdl_bot.py", line 107, in wrapper
    return func(client, message)
  File "/ytdlbot/ytdlbot/ytdl_bot.py", line 337, in download_handler
    redis.user_count(chat_id)
  File "/ytdlbot/ytdlbot/database.py", line 183, in user_count
    self.r.hincrby("metrics", user_id)
  File "/usr/local/lib/python3.10/site-packages/redis/commands/core.py", line 4877, in hincrby
    return self.execute_command("HINCRBY", name, key, amount)
  File "/usr/local/lib/python3.10/site-packages/redis/client.py", line 1255, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/usr/local/lib/python3.10/site-packages/redis/connection.py", line 1442, in get_connection
    connection.connect()
  File "/usr/local/lib/python3.10/site-packages/redis/connection.py", line 704, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error -2 connecting to redis:6379. Name does not resolve.
[2023-04-27 21:12:46 dispatcher.py:235 E] Telegram says: [400 MESSAGE_TOO_LONG] - The message text is over 4096 characters (caused by "messages.SendMessage")
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/pyrogram/dispatcher.py", line 224, in handler_worker
    await self.loop.run_in_executor(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/ytdlbot/ytdlbot/ytdl_bot.py", line 215, in ping_handler
    client.send_message(chat_id, f"{bot_info.split('CPU')[0]}")
  File "/usr/local/lib/python3.10/site-packages/pyrogram/sync.py", line 78, in async_to_sync_wrap
    return asyncio.run_coroutine_threadsafe(coroutine, main_loop).result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 458, in result
    return self.__get_result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.10/site-packages/pyrogram/methods/messages/send_message.py", line 128, in send_message
    r = await self.send(
  File "/usr/local/lib/python3.10/site-packages/pyrogram/methods/advanced/send.py", line 77, in send
    r = await self.session.send(
  File "/usr/local/lib/python3.10/site-packages/pyrogram/session/session.py", line 362, in send
    return await self._send(data, timeout=timeout)
  File "/usr/local/lib/python3.10/site-packages/pyrogram/session/session.py", line 332, in _send
    RPCError.raise_it(result, type(data))
  File "/usr/local/lib/python3.10/site-packages/pyrogram/errors/rpc_error.py", line 91, in raise_it
    raise getattr(
pyrogram.errors.exceptions.bad_request_400.MessageTooLong: Telegram says: [400 MESSAGE_TOO_LONG] - The message text is over 4096 characters (caused by "messages.SendMessage")
`

**Comment by BennyThink** [comment]
setup redis.  See readme for details.

**Comment by BennyThink** [comment]
also remember maybe you need to change REDIS environment variable to `localhost`

**Comment by tizosa** [comment]
I wanted to run it in docker as if it is heroku. I don't need to enable cache & VIP mode.

**Comment by BennyThink** [comment]
then it should be optional. 
```
class Redis:
    def __init__(self):
        if REDIS:
            self.r = redis.StrictRedis(host=REDIS, db=0, decode_responses=True)
        else:
            self.r = fakeredis.FakeStrictRedis(host=REDIS, db=0, decode_responses=True)
```

if redis is not available, then it'll try fake redis. Pull the latest code and try again.

**Comment by BennyThink** [comment]
just fixed, pull the code and try again
