### ISSUE TITLE
400 Bad Request error at command `/settings`

### ISSUE THREAD

**Issue by ashmat98** [tgbot-collection/ytdlbot#273]
```
ytdl_1    | Traceback (most recent call last):
ytdl_1    |   File "/usr/local/lib/python3.10/site-packages/pyrogram/dispatcher.py", line 224, in handler_worker
ytdl_1    |     await self.loop.run_in_executor(
ytdl_1    |   File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
ytdl_1    |     result = self.fn(*self.args, **self.kwargs)
ytdl_1    |   File "/ytdlbot/ytdlbot/ytdl_bot.py", line 279, in settings_handler
ytdl_1    |     client.send_message(chat_id, BotText.settings.format(data[1], data[2]) + mode_text, reply_markup=markup)
ytdl_1    |   File "/usr/local/lib/python3.10/site-packages/pyrogram/sync.py", line 78, in async_to_sync_wrap
ytdl_1    |     return asyncio.run_coroutine_threadsafe(coroutine, main_loop).result()
ytdl_1    |   File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 458, in result
ytdl_1    |     return self.__get_result()
ytdl_1    |   File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
ytdl_1    |     raise self._exception
ytdl_1    |   File "/usr/local/lib/python3.10/site-packages/pyrogram/methods/messages/send_message.py", line 128, in send_message
ytdl_1    |     r = await self.send(
ytdl_1    |   File "/usr/local/lib/python3.10/site-packages/pyrogram/methods/advanced/send.py", line 77, in send
ytdl_1    |     r = await self.session.send(
ytdl_1    |   File "/usr/local/lib/python3.10/site-packages/pyrogram/session/session.py", line 362, in send
ytdl_1    |     return await self._send(data, timeout=timeout)
ytdl_1    |   File "/usr/local/lib/python3.10/site-packages/pyrogram/session/session.py", line 332, in _send
ytdl_1    |     RPCError.raise_it(result, type(data))
ytdl_1    |   File "/usr/local/lib/python3.10/site-packages/pyrogram/errors/rpc_error.py", line 80, in raise_it
ytdl_1    |     raise getattr(
ytdl_1    | pyrogram.errors.exceptions.bad_request_400.BadRequest: Telegram says: [400 Bad Request] - [400 ENTITY_BOUNDS_INVALID] (caused by "messages.SendMessage")
```

**Comment by ashmat98** [comment]
I temporarily solved the problem with this (line 280 of `ytdl_bot.py`)

`client.send_message(chat_id, BotText.settings.format(data[1]+".", data[2]+".") + mode_text, reply_markup=markup)`

sometimes `data[1]` and `data[2]` are empty strings

**Comment by BennyThink** [comment]
thanks, I will investigate and fix accordingly
