### ISSUE TITLE
unable Playlist download problem

### ISSUE THREAD

**Issue by CevreMuhendisi** [tgbot-collection/ytdlbot#306]
i cant download playlist, please fix it 

Traceback (most recent call last):
  File "/ytdlbot/ytdlbot/tasks.py", line 152, in ytdl_download_entrance
    ytdl_normal_download(client, bot_msg, url)
  File "/ytdlbot/ytdlbot/tasks.py", line 265, in ytdl_normal_download
    video_paths = ytdl_download(url, temp_dir.name, bot_msg)
  File "/ytdlbot/ytdlbot/downloader.py", line 203, in ytdl_download
    raise Exception(error)
Exception: Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1560, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/yt_dlp/utils/_utils.py", line 2893, in 
    return type(self.ydl)._handle_extraction_exceptions(lambda _, i: self._entries[i])(self.ydl, i)
  File "/usr/local/lib/python3.10/site-packages/yt_dlp/utils/_utils.py", line 2661, in __getitem__
    self._cache.extend(itertools.islice(self._iterable, n))
  File "/usr/local/lib/python3.10/site-packages/yt_dlp/extractor/youtube.py", line 4930, in _entries
    response = self._extract_response(
  File "/usr/local/lib/python3.10/site-packages/yt_dlp/extractor/youtube.py", line 951, in _extract_response
    for retry in self.RetryManager():
  File "/usr/local/lib/python3.10/site-packages/yt_dlp/utils/_utils.py", line 5634, in __iter__
    self.error_callback(self.error, self.attempt, self.retries)
  File "/usr/local/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 3749, in _error_or_warning
    RetryManager.report_retry(
  File "/usr/local/lib/python3.10/site-packages/yt_dlp/utils/_utils.py", line 5642, in report_retry
    raise e
yt_dlp.utils.ExtractorError: Incomplete data received

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/ytdlbot/ytdlbot/downloader.py", line 193, in ytdl_download
    ydl.download([url])
  File "/usr/local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3485, in download
    self.__download_wrapper(self.extract_info)(
  File "/usr/local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3460, in wrapper
    res = func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1549, in extract_info
    return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
  File "/usr/local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1560, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1709, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1838, in process_ie_result
    return self.__process_playlist(ie_result, download)
  File "/usr/local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1913, in __process_playlist
    entries = resolved_entries = list(entries)
  File "/usr/local/lib/python3.10/site-packages/yt_dlp/utils/_utils.py", line 811, in _iter
    for x in iterable:
  File "/usr/local/lib/python3.10/site-packages/yt_dlp/utils/_utils.py", line 2858, in get_requested_items
    for i, entry in self[index]:
  File "/usr/local/lib/python3.10/site-packages/yt_dlp/utils/_utils.py", line 2920, in __getitem__
    entry = self._getter(i)
  File "/usr/local/lib/python3.10/site-packages/yt_dlp/utils/_utils.py", line 2893, in get_entry
    return type(self.ydl)._handle_extraction_exceptions(lambda _, i: self._entries[i])(self.ydl, i)
  File "/usr/local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1578, in wrapper
    self.report_error(str(e), e.format_traceback())
  File "/usr/local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1042, in report_error
    self.trouble(f'{self._format_err("ERROR:", self.Styles.ERROR)} {message}', *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 981, in trouble
    raise DownloadError(message, exc_info)
yt_dlp.utils.DownloadErr

**Comment by SanujaNS** [comment]
Hello @CevreMuhendisi,

Can you send the playlist URL that gave you this error?

Also It would be better if you can provide the full log(terminal output/error) as a paste using [https://pastebin.com/](https://pastebin.com/).

**Comment by CevreMuhendisi** [comment]
im using docker image ( bennythink/ytdlbot )

https://pastebin.com/GJGXa3sy

**Comment by CevreMuhendisi** [comment]
@SanujaNS 
Is there any progress, my friend?

**Comment by SanujaNS** [comment]
@CevreMuhendisi
We're trying to figure out the problem.
In the meantime,
Would you try deleting current container and rerunning it?

**Comment by CevreMuhendisi** [comment]
@SanujaNS it didnt work

**Comment by SanujaNS** [comment]
We'll let you know as soon as we have more information.

**Comment by SanujaNS** [comment]
You are running an old version of docker image,
![Screenshot_20231029_140453](https://github.com/tgbot-collection/ytdlbot/assets/66342986/e37752d0-55d6-4a7f-996e-b1d3fefbb766)
![photo_2023-10-29_14-05-51](https://github.com/tgbot-collection/ytdlbot/assets/66342986/63e2eec0-23f7-4055-aa8f-316f30077cc1)

Try running,
```bash
docker run bennythink/ytdlbot:latest
```
after deleting current bot container.

FYI,
1. Get Container ID,
```bash
docker ps -a
```
2. Delete container,
```bash
docker rm -f "CONTAINER ID"
```
3. Delete Image,
```bash
docker rmi -f bennythink/ytdlbot
```
4. Now run with your env,
```bash
docker run -e APP_ID=111 -e APP_HASH=111 -e TOKEN=370FXI bennythink/ytdlbot:latest
```

**Comment by CevreMuhendisi** [comment]
> You are running an old version of docker image, ![Screenshot_20231029_140453](https://user-images.githubusercontent.com/66342986/278859724-e37752d0-55d6-4a7f-996e-b1d3fefbb766.png) ![photo_2023-10-29_14-05-51](https://user-images.githubusercontent.com/66342986/278859758-63e2eec0-23f7-4055-aa8f-316f30077cc1.jpg)
> 
> Try running,
> 
> ```shell
> docker run bennythink/ytdlbot:latest
> ```
> 
> after deleting current bot container.
> 
> FYI,
> 
> 1. Get Container ID,
> 
> ```shell
> docker ps -a
> ```
> 
> 2. Delete container,
> 
> ```shell
> docker rm -f "CONTAINER ID"
> ```
> 
> 3. Delete Image,
> 
> ```shell
> docker rmi -f bennythink/ytdlbot
> ```
> 
> 4. Now run with your env,
> 
> ```shell
> docker run -e APP_ID=111 -e APP_HASH=111 -e TOKEN=370FXI bennythink/ytdlbot:latest
> ```

When I get home, I will try. Thank you. Can you edit the command on the main page?

![Screenshot_2023-10-29-11-50-08-542-edit_com kiwibrowser browser](https://github.com/tgbot-collection/ytdlbot/assets/59526034/602d5de4-8885-4856-8302-8502de21cdeb)

**Comment by SanujaNS** [comment]
Okay I will submit a PR for that.

Let us know your situation after...

**Comment by CevreMuhendisi** [comment]
@SanujaNS doesnt work my friend

https://pastebin.com/PYnvwJ99

**Comment by BennyThink** [comment]
Can you try
```bash
yt-dlp "https://www.youtube.com/playlist?list=PLvQ068xq8z3D3ix9tFaMIcSe3LgpyCTHR"
```

Feels like a server side issue.

**Comment by SanujaNS** [comment]
Looks like there's a problem with data extraction of yt-dlp.

Issues looks alike on /yt-dlp,
[ [youtube:tab] "Incomplete data received" on "Redownloading playlist API JSON with unavailable videos" #8283 ](https://github.com/yt-dlp/yt-dlp/issues/8283)
[ Intermittent "Incomplete data received" errors when downloading YouTube playlist JSON #8206 ](https://github.com/yt-dlp/yt-dlp/issues/8206)

**Comment by BennyThink** [comment]
try to upgrade to the latest image. Fixed in upstream

**Comment by Oio0** [comment]
Issues still exist.
```
yt-dlp "https://www.youtube.com/playlist?list=PLvQ068xq8z3D3ix9tFaMIcSe3LgpyCTHR" 
[youtube:tab] Extracting URL: https://www.youtube.com/playlist?list=PLvQ068xq8z3D3ix9tFaMIcSe3LgpyCTHR
[youtube:tab] PLvQ068xq8z3D3ix9tFaMIcSe3LgpyCTHR: Downloading webpage
[youtube:tab] PLvQ068xq8z3D3ix9tFaMIcSe3LgpyCTHR: Redownloading playlist API JSON with unavailable videos
[download] Downloading playlist: Excel Kısa Videolar
[youtube:tab] PLvQ068xq8z3D3ix9tFaMIcSe3LgpyCTHR page 1: Downloading API JSON
WARNING: [youtube:tab] Incomplete data received. Retrying (1/3)...
[youtube:tab] PLvQ068xq8z3D3ix9tFaMIcSe3LgpyCTHR page 1: Downloading API JSON
WARNING: [youtube:tab] Incomplete data received. Retrying (2/3)...
[youtube:tab] PLvQ068xq8z3D3ix9tFaMIcSe3LgpyCTHR page 1: Downloading API JSON
WARNING: [youtube:tab] Incomplete data received. Retrying (3/3)...
[youtube:tab] PLvQ068xq8z3D3ix9tFaMIcSe3LgpyCTHR page 1: Downloading API JSON
WARNING: [youtube:tab] Incomplete data received. Giving up after 3 retries
[youtube:tab] Playlist Excel Kısa Videolar: Downloading 60 items of 60
```
