### ISSUE TITLE
what to name .env file 

### ISSUE THREAD

**Issue by N30Z3N** [tgbot-collection/ytdlbot#314]
for deployment without docker what should I name .env file

**Comment by SanujaNS** [comment]
If this ```env/ytdl.env``` doesn't work,
You can directly change values in ```ytdlbot/ytdlbot/config.py```
![Screenshot_20231204_141744](https://github.com/tgbot-collection/ytdlbot/assets/66342986/d52626d2-329b-4711-ad33-bf7af345c2e1)
I'm using the bot this way and it works fine.

**Comment by BennyThink** [comment]
you can either:
1. change config.py
2. export TOKEN=123 REDIS=localhost and then python ytdl_bot.py

**Comment by N30Z3N** [comment]
did like @SanujaNS said boom some error 

```[2023-12-05 07:10:09 dispatcher.py:253 E] 'str' object has no attribute 'name'
Traceback (most recent call last):
  File "/root/venv/lib/python3.11/site-packages/pyrogram/dispatcher.py", line 242, in handler_worker
    await self.loop.run_in_executor(
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/ytdlbot/ytdlbot/ytdl_bot.py", line 119, in start_handler
    client.send_chat_action(from_id, "typing")
  File "/root/venv/lib/python3.11/site-packages/pyrogram/sync.py", line 78, in async_to_sync_wrap
    return asyncio.run_coroutine_threadsafe(coroutine, main_loop).result()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/root/venv/lib/python3.11/site-packages/pyrogram/methods/messages/send_chat_action.py", line 68, in send_chat_action
    action_name = action.name.lower()
                  ^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'name'```

**Comment by BennyThink** [comment]
it seems like you installed the wrong version of pyrogram.

**Comment by SanujaNS** [comment]
> did like @SanujaNS said boom some error
> 
> ```
> Traceback (most recent call last):
>   File "/root/venv/lib/python3.11/site-packages/pyrogram/dispatcher.py", line 242, in handler_worker
>     await self.loop.run_in_executor(
>   File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
>     result = self.fn(*self.args, **self.kwargs)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/root/ytdlbot/ytdlbot/ytdl_bot.py", line 119, in start_handler
>     client.send_chat_action(from_id, "typing")
>   File "/root/venv/lib/python3.11/site-packages/pyrogram/sync.py", line 78, in async_to_sync_wrap
>     return asyncio.run_coroutine_threadsafe(coroutine, main_loop).result()
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 456, in result
>     return self.__get_result()
>            ^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
>     raise self._exception
>   File "/root/venv/lib/python3.11/site-packages/pyrogram/methods/messages/send_chat_action.py", line 68, in send_chat_action
>     action_name = action.name.lower()
>                   ^^^^^^^^^^^
> AttributeError: 'str' object has no attribute 'name'```
> ```

Hello @N30Z3N,

We'd love to help you out, but the information you've provided isn't sufficient for us to offer a more accurate solution for the problem.

**share what you did step by step till you start the bot with us.**

**Also please provide the complete terminal output via [https://pastebin.com](https://pastebin.com) for example like this one [https://pastebin.com/raw/PYnvwJ99](https://pastebin.com/raw/PYnvwJ99).**

**Comment by N30Z3N** [comment]
@SanujaNS don't know man I just tried it again and changed bot token it worked thanks for quick response just another question is it possible to add login/pass for yt-dlp supported sites

**Comment by N30Z3N** [comment]
> Hello @N30Z3N,
> 
> We'd love to help you out, but the information you've provided isn't sufficient for us to offer a more accurate solution for the problem.
> 
> **share what you did step by step till you start the bot with us.**
> 
> **Also please provide the complete terminal output via https://pastebin.com for example like this one https://pastebin.com/raw/PYnvwJ99.**

https://pastebin.com/63skLHik well again different error ig do you guys have discussion group or something will be much helpful that me calling you guys again and again on github

**Comment by SanujaNS** [comment]
> > Hello @N30Z3N,
> > We'd love to help you out, but the information you've provided isn't sufficient for us to offer a more accurate solution for the problem.
> > **share what you did step by step till you start the bot with us.**
> > **Also please provide the complete terminal output via https://pastebin.com for example like this one https://pastebin.com/raw/PYnvwJ99.**
> 
> https://pastebin.com/63skLHik well again different error ig do you guys have discussion group or something will be much helpful that me calling you guys again and again on github

There isn't yet. You can contact me through [Telegram - https://t.me/SanujaNS](https://t.me/SanujaNS).

As for the error,
delete the session file and start the bot again
session file = 
![Screenshot_20231205_184653](https://github.com/tgbot-collection/ytdlbot/assets/66342986/086b5ba1-0a69-4f48-a20f-9ffae51797cc)

**(You may need to delete the session file every time bot restarts. It's a problem, @BennyThink  working on it.)**

**Comment by SanujaNS** [comment]
FYI,
Bot Start Process

```
git clone --branch pyrogram-v2 "https://github.com/tgbot-collection/ytdlbot.git

cd ytdlbot/

python -m venv venv

source venv/bin/activate

pip install --upgrade pip

pip install -r requirements.txt

cd ytdlbot/
```
Change values in `config.py` accordingly

Finally run the bot,
```python
python ytdl_bot.py
```
