### ISSUE TITLE
/sub channel not working

### ISSUE THREAD

**Issue by 2019YKL** [tgbot-collection/ytdlbot#317]
The subscription function for the channel seems to have failed, as I was unable to subscribe using the test link.

/sub https://www.youtube.com/channel/UCGg-UqjRgzhYDPJMr-9HXCg

![image](https://github.com/tgbot-collection/ytdlbot/assets/51532948/e59c4fd8-c971-411f-bd8b-82bed645992a)

logs:

[2023-12-06 16:30:03 ytdl_bot.py:103 I] user 8555888 check passed for group/channel -1001388889088.
[2023-12-06 16:30:03 ytdl_bot.py:384 I] start ['sub_count']
[2023-12-06 16:30:03 database.py:111 I] Setting metrics: bad_request
[2023-12-06 16:30:04 connection.py:56 I] Connecting...
[2023-12-06 16:30:06 connection.py:63 I] Connected! Production DC5 (media) - IPv4 - TCPAbridgedO
[2023-12-06 16:30:06 session.py:272 I] NetworkTask started
[2023-12-06 16:30:07 connection.py:77 I] Disconnected
[2023-12-06 16:30:07 session.py:288 I] NetworkTask stopped
[2023-12-06 16:30:07 session.py:174 I] Session stopped
[2023-12-06 16:30:07 connection.py:56 I] Connecting...
[2023-12-06 16:30:07 connection.py:63 I] Connected! Production DC5 (media) - IPv4 - TCPAbridgedO
[2023-12-06 16:30:07 session.py:272 I] NetworkTask started
[2023-12-06 16:30:08 session.py:131 I] Session initialized: Layer 140
[2023-12-06 16:30:08 session.py:132 I] Device: CPython 3.11.6 - Pyrogram 1.4.16
[2023-12-06 16:30:08 session.py:133 I] System: Linux 5.4.0-28-generic (EN)
[2023-12-06 16:30:08 session.py:148 I] Session started
[2023-12-06 16:30:08 session.py:250 I] PingTask started
[2023-12-06 16:30:08 session.py:269 I] PingTask stopped
[2023-12-06 16:30:08 connection.py:77 I] Disconnected
[2023-12-06 16:30:08 session.py:288 I] NetworkTask stopped
[2023-12-06 16:30:08 session.py:174 I] Session stopped
[2023-12-06 16:34:11 dispatcher.py:235 E] 'items'
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/pyrogram/dispatcher.py", line 224, in handler_worker
    await self.loop.run_in_executor(
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ytdlbot/ytdlbot/ytdl_bot.py", line 155, in subscribe_handler
    result = channel.subscribe_channel(chat_id, link)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ytdlbot/ytdlbot/channel.py", line 26, in subscribe_channel
    data = self.get_channel_info(share_link)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ytdlbot/ytdlbot/channel.py", line 91, in get_channel_info
    snippet = data["items"][0]["snippet"]
              ~~~~^^^^^^^^^
KeyError: 'items'

I don't understand what happened, thank you for your reading.❤

**Comment by BennyThink** [comment]
Can you try again? Feels like it's caused by running out of API quota.

**Comment by BennyThink** [comment]
Oh just realized you're using your own bot? apply youtube api key https://developers.google.com/youtube/v3/getting-started

**Comment by 2019YKL** [comment]
> Oh just realized you're using your own bot? apply youtube api key https://developers.google.com/youtube/v3/getting-started

Thank you very much for your response. It helped me understand the issue. After testing, I found that your official example works fine. I will follow your guidance to resolve the issue with my own Bot.

**Comment by BennyThink** [comment]
Cool, apply an API key from the above link should work. Let me know if anything goes wrong.
