### ISSUE TITLE
Bot Not working

### ISSUE THREAD

**Issue by luciferluci2** [tgbot-collection/ytdlbot#37]
FileNotFoundError: [Errno 2] No such file or directory: '/var/log/ytdl.log'
2022-01-18T07:27:42.692909+00:00 app[worker.1]: Job "auto_restart (trigger: interval[0:00:05], next run at: 2022-01-18 15:27:47 CST)" raised an exception
2022-01-18T07:27:42.692922+00:00 app[worker.1]: Traceback (most recent call last):
2022-01-18T07:27:42.692923+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/apscheduler/executors/base.py", line 125, in run_job
2022-01-18T07:27:42.692923+00:00 app[worker.1]:     retval = job.func(*job.args, **job.kwargs)
2022-01-18T07:27:42.692924+00:00 app[worker.1]:   File "/app/ytdlbot/utils.py", line 213, in auto_restart
2022-01-18T07:27:42.692924+00:00 app[worker.1]:     with open("/var/log/ytdl.log") as f:
2022-01-18T07:27:42.692925+00:00 app[worker.1]: FileNotFoundError: [Errno 2] No such file or directory: '/var/log/ytdl.log'
2022-01-18T07:27:47.692831+00:00 app[worker.1]: Job "auto_restart (trigger: interval[0:00:05], next run at: 2022-01-18 15:27:52 CST)" raised an exception
2022-01-18T07:27:47.692841+00:00 app[worker.1]: Traceback (most recent call last):
2022-01-18T07:27:47.692841+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/apscheduler/executors/base.py", line 125, in run_job
2022-01-18T07:27:47.692841+00:00 app[worker.1]:     retval = job.func(*job.args, **job.kwargs)
2022-01-18T07:27:47.692842+00:00 app[worker.1]:   File "/app/ytdlbot/utils.py", line 213, in auto_restart
2022-01-18T07:27:47.692842+00:00 app[worker.1]:     with open("/var/log/ytdl.log") as f:
2022-01-18T07:27:47.692843+00:00 app[worker.1]: FileNotFoundError: [Errno 2] No such file or directory: '/var/log/ytdl.log'
2022-01-18T07:27:52.692770+00:00 app[worker.1]: Job "auto_restart (trigger: interval[0:00:05], next run at: 2022-01-18 15:27:57 CST)" raised an exception
2022-01-18T07:27:52.692781+00:00 app[worker.1]: Traceback (most recent call last):
2022-01-18T07:27:52.692781+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/apscheduler/executors/base.py", line 125, in run_job
2022-01-18T07:27:52.692782+00:00 app[worker.1]:     retval = job.func(*job.args, **job.kwargs)
2022-01-18T07:27:52.692782+00:00 app[worker.1]:   File "/app/ytdlbot/utils.py", line 213, in auto_restart
2022-01-18T07:27:52.692782+00:00 app[worker.1]:     with open("/var/log/ytdl.log") as f:
2022-01-18T07:27:52.692783+00:00 app[worker.1]: FileNotFoundError: [Errno 2] No such file or directory: '/var/log/ytdl.log'

**Comment by BennyThink** [comment]
fixed. fetch and try again
