### ISSUE TITLE
/ping does not work

### ISSUE THREAD

**Issue by EDM115** [tgbot-collection/ytdlbot#65]
I don't know if it's an owner-only feature, but ping command systematically fails :

`Runtime information is not available outside of docker container.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/tgbot_ping/__init__.py", line 19, in get_runtime
    info, raw_data = __get_container_info(container_name, display_name)
  File "/usr/local/lib/python3.9/site-packages/tgbot_ping/__init__.py", line 62, in __get_container_info
    cpu = __calculate_cpu_percent(stats)
  File "/usr/local/lib/python3.9/site-packages/tgbot_ping/__init__.py", line 78, in __calculate_cpu_percent
    system_delta = float(d["cpu_stats"]["system_cpu_usage"]) - \
KeyError: 'system_cpu_usage'`

**Comment by EDM115** [comment]
Okay okay 😇 just, this was on your bot, not on a deployed one 😅

**Comment by BennyThink** [comment]
Yeah, sometimes it'll throw some exception. But the bot is actually running. I'll fix the utility later.

**Comment by BennyThink** [comment]
fixed.
