### ISSUE TITLE
Bot going not well

### ISSUE THREAD

**Issue by gtjl12** [tgbot-collection/ytdlbot#89]
It seems the bot doesn't run well on my server. I don't know where goes wrong.
My server OS is CentOS 8.5，python's version is 3.6.8
 
when I send '/about' command ,the bot replies the repo link  normally.
when send '/ping' command , error message is :
```
Telegram says: [400 MESSAGE_TOO_LONG] - The message text is over 4096 characters (caused by "messages.SendMessage")
```

When send a video  link  or  '/setting' command  ,  error message is as follows:
```
[2022-04-07 09:20:54 dispatcher.py:136 I] Started 100 HandlerTasks
[2022-04-07 09:21:01 dispatcher.py:235 E] module 'six' has no attribute 'ensure_str'
Traceback (most recent call last):
  File "/usr/local/lib64/python3.6/site-packages/pyrogram/dispatcher.py", line 228, in handler_worker
    *args
  File "/usr/lib64/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "ytdl_bot.py", line 76, in wrapper
    return func(client, message)
  File "ytdl_bot.py", line 265, in download_handler
    red.user_count(chat_id)
  File "/root/ytdlbot/ytdlbot/db.py", line 133, in user_count
    self.r.hincrby("metrics", user_id)
  File "/usr/local/lib/python3.6/site-packages/redis/commands/core.py", line 3717, in hincrby
    return self.execute_command("HINCRBY", name, key, amount)
  File "/usr/local/lib/python3.6/site-packages/redis/client.py", line 1180, in execute_command
    lambda error: self._disconnect_raise(conn, error),
  File "/usr/local/lib/python3.6/site-packages/redis/retry.py", line 45, in call_with_retry
    return do()
  File "/usr/local/lib/python3.6/site-packages/redis/client.py", line 1178, in <lambda>
    conn, command_name, *args, **options
  File "/usr/local/lib/python3.6/site-packages/redis/client.py", line 1152, in _send_command_parse_response
    conn.send_command(*args)
  File "/usr/local/lib/python3.6/site-packages/redis/connection.py", line 796, in send_command
    self.pack_command(*args), check_health=kwargs.get("check_health", True)
  File "/usr/local/lib/python3.6/site-packages/redis/connection.py", line 777, in send_packed_command
    self._sock.sendall(item)
  File "/usr/local/lib/python3.6/site-packages/fakeredis/_server.py", line 836, in sendall
    self._parser.send(data)
  File "/usr/local/lib/python3.6/site-packages/fakeredis/_server.py", line 753, in _parse_commands
    self._process_command(fields)
  File "/usr/local/lib/python3.6/site-packages/fakeredis/_server.py", line 843, in _process_command
    func, func_name = self._name_to_func(fields[0])
  File "/usr/local/lib/python3.6/site-packages/fakeredis/_server.py", line 822, in _name_to_func
    name = six.ensure_str(name, encoding='utf-8', errors='replace')
AttributeError: module 'six' has no attribute 'ensure_str'
^C[2022-04-07 09:21:22 idle.py:77 I] Stop signal received (SIGINT). Exiting...
[2022-04-07 09:21:23 dispatcher.py:149 I] Stopped 100 HandlerTasks
[2022-04-07 09:21:23 session.py:269 I] PingTask stopped
[2022-04-07 09:21:23 connection.py:77 I] Disconnected
[2022-04-07 09:21:23 session.py:288 I] NetworkTask stopped
[2022-04-07 09:21:23 session.py:174 I] Session stopped
```

**Comment by BennyThink** [comment]
it's actually doesn't matter. You'll have to use docker and socat if you want ping to work normally.

**Comment by gtjl12** [comment]
> it's actually doesn't matter. You'll have to use docker and socat if you want ping to work normally.

Alright, But when I send a video link , the bot replies noting , and the download task on server seems doesn't start either.

**Comment by BennyThink** [comment]
Okay can you provide me with the config(redacted credentials) and logs?

**Comment by gtjl12** [comment]
Sorry for replying late.
I didn't find any file named 'ytdl.log' in my machine.
And which config file should I give you? I installed the bot following this [instruction](https://github.com/tgbot-collection/ytdlbot#run-natively-on-your-machine)，didn't manually modify any config settings.

**Comment by BennyThink** [comment]
Using docker? Or run natively on your machine?

Docker: docker logs
Nativity: directly from terminal or /var/log/ytdl.log

**Comment by gtjl12** [comment]
I run the bot directly on my own machine.
I guess the problem is related to the version of Python.
The original Python on my machine is 3.6.8, and there are some plugins in 'requirements.txt' that do not support older version of Python (for example, Python 3.6 only supports celery 5.1 or earlier).
Today I updated Python to the latest version(3.10.4) , reinstalled the plugins in 'requirements.txt', all problems are solved, the bot is running very well.
Thank you very much for your help, I will close this issue.
